version: '3'
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-demo
    ports:
      - "8080:8080"
    networks:
      - spring-app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - spring-app
    networks:
      - spring-app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
    command: >
            certonly --webroot --webroot-path=/etc/letsencrypt/webroot \
            --email huynhvanvong2002@gmail.com \
            --agree-tos \
            --no-eff-email \
            -d m2m.lerndevops.click
    depends_on:
      - nginx
    networks:
      - spring-app-network

networks:
  spring-app-network:
