version: '3'
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-demo
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx-spring-app
    depends_on:
      - spring-app